config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    collection do
      get :search
    end
  end

  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  enum status: { 'pending': 0, 'progress': 1, 'completed': 2 }

  validate :end_after_start
  validates :title, :content, :start_time, :end_time, presence: true
  validates :status, inclusion: { in: statuses }
  
  scope :end_time, -> { order(end_time: :desc) }

  private

  def end_after_start
    return if start_time.blank? || end_time.blank?

    if end_time < start_time
      errors.add(:end_time, :cant_end_after_start)
    end
 end

 def self.search_params(search = nil)
   return all if search.nil?
   where(['title || status LIKE ?', "%#{search}%"])
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: ENV["http_auth_username"], password: ENV["http_auth_password"] if Rails.env.production?
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    # 到「步驟17: 增加分頁功能」，先暫時用 all
    @tasks = Task.end_time
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def search
    @tasks = Task.search_params(params[:search_title]).search_params(params[:search_status]).end_time
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to root_path, notice: t("new_success")
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to root_path, notice: t("update_success")
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    if @task.destroyed?
      notice = t("delete_success")
    else
      notice = t("delete_fail")
    end
    redirect_to root_path, notice: notice
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :content, :start_time, :end_time, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_select
    Task.statuses.keys.map{ |k| [I18n.t("enums.task.status.#{k}"), k] }
  end

  def options_select
    options_for_select([[t("enums.task.status.pending"), 0],
                        [t("enums.task.status.progress"), 1],
                        [t("enums.task.status.completed"), 2]])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To Do Task</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_common.html.erb
<%= form_tag search_tasks_path, method: 'get' do %>
  <%= text_field_tag :search_title, params[:search], placeholder: t("search_placeholder") %>
  <%= select_tag :search_status, options_select %>
  <%= submit_tag t("search") %>
<% end %>
<table>
  <thead>
    <tr>
      <th><%= t("title") %></th>
      <th><%= t("content") %></th>
      <th><%= t("start_time") %></th>
      <th><%= t("end_time") %></th>
      <th><%= t("status") %></th>
      <th colspan="2" ><%= t("action") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <th><%= link_to task.title, task_path(task) %></th>
        <th><%= task.content %></th>
        <th><%= task.start_time.strftime('%Y-%m-%d %H:%M') %></th>
        <th><%= task.end_time.strftime('%Y-%m-%d %H:%M') %></th>
        <th><%= I18n.t("enums.task.status")[:"#{task.status}"] %></th>
        <th><%= link_to t("edit"), edit_task_path(task) %></th>
        <th><%= link_to t("delete"), task_path(task), method: :delete, data: { confirm: t("delete_confirm") } %></th>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to t("new_task"), new_task_path %>

app/views/tasks/_form.html.erb
<% if task.errors.any? %>
  <ul>
    <% task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(task) do |form| %>
  <div class="field">
    <%= form.label :title, t("title") %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content, t("content") %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :start_time, t("start_time") %>
    <%= form.datetime_field :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time, t("end_time") %>
    <%= form.datetime_field :end_time %>
  </div>

  <div class="field">
    <%= form.label :status, t("status") %>
    <%= form.select :status, status_select %>
  </div>

  <div class="field">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1><%= t("task_edit") %></h1>

<%= render 'form', task: @task %>

<%= link_to t("root"), root_path %>

app/views/tasks/index.html.erb
<h1><%= t("task_index") %></h1>

<%= render 'common' %>

app/views/tasks/new.html.erb
<h1><%= t("task_new") %></h1>

<%= render 'form', task: @task %>

<%= link_to t("root"), root_path %>

app/views/tasks/search.html.erb
<h1><%= t("task_search") %></h1>

<%= render 'common', task: @tasks %>

<%= link_to t("root"), root_path %>

app/views/tasks/show.html.erb
<h1><%= t("task_show") %></h1>
<p><%= t("title") %>: <%= @task.title %></p>
<p><%= t("content") %>: <%= @task.content %></p>
<p><%= t("start_time") %>: <%= @task.start_time.strftime('%Y-%m-%d %H:%M') %></p>
<p><%= t("end_time") %>: <%= @task.end_time.strftime('%Y-%m-%d %H:%M') %></p>
<p><%= t("status") %>: <%= I18n.t("enums.task.status")[:"#{@task.status}"] %></p>

<%= link_to t("root"), root_path %>